// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr0ODgcQTFBICq62wYrQ5pLeMXdGT0utk',
    appId: '1:960682405618:web:491cc479d041c2ccd62a6b',
    messagingSenderId: '960682405618',
    projectId: 'zero-gym-database',
    authDomain: 'zero-gym-database.firebaseapp.com',
    storageBucket: 'zero-gym-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwIsGMGQovK1Iqy2th43wp5p3vPzH9RPM',
    appId: '1:960682405618:android:8ec820c307322e45d62a6b',
    messagingSenderId: '960682405618',
    projectId: 'zero-gym-database',
    storageBucket: 'zero-gym-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ZD5-kf8Y4LmymJ-xTni0lYYiWqKWXUU',
    appId: '1:960682405618:ios:06c31f0f92cbcb07d62a6b',
    messagingSenderId: '960682405618',
    projectId: 'zero-gym-database',
    storageBucket: 'zero-gym-database.firebasestorage.app',
    iosBundleId: 'com.example.zeroGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ZD5-kf8Y4LmymJ-xTni0lYYiWqKWXUU',
    appId: '1:960682405618:ios:06c31f0f92cbcb07d62a6b',
    messagingSenderId: '960682405618',
    projectId: 'zero-gym-database',
    storageBucket: 'zero-gym-database.firebasestorage.app',
    iosBundleId: 'com.example.zeroGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr0ODgcQTFBICq62wYrQ5pLeMXdGT0utk',
    appId: '1:960682405618:web:ab8c069b530af351d62a6b',
    messagingSenderId: '960682405618',
    projectId: 'zero-gym-database',
    authDomain: 'zero-gym-database.firebaseapp.com',
    storageBucket: 'zero-gym-database.firebasestorage.app',
  );
}
